In [29]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [30]:
env = gym.make("FrozenLake-v0")

In [31]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [33]:
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    
    # initialize new episode params
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
            
        # Take new action
        new_state, reward, done, info = env.step(action)

        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        # Set new state
        state = new_state
        
        # Add new reward        
        rewards_current_episode += reward 
        
        if done == True: 
            break

    # Exploration rate decay 
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    

# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)


********Average reward per thousand episodes********

1000 :  0.04100000000000003
2000 :  0.22000000000000017
3000 :  0.3840000000000003
4000 :  0.5740000000000004
5000 :  0.6430000000000005
6000 :  0.6620000000000005
7000 :  0.6720000000000005
8000 :  0.6760000000000005
9000 :  0.6690000000000005
10000 :  0.7180000000000005


********Q-table********

[[0.56527855 0.53834512 0.55853108 0.55820097]
 [0.23558289 0.32235652 0.23435934 0.54548745]
 [0.42007724 0.3975475  0.41614258 0.51940978]
 [0.31152876 0.25129185 0.31629032 0.49832735]
 [0.5823963  0.46888377 0.42426871 0.36524379]
 [0.         0.         0.         0.        ]
 [0.45413424 0.15174177 0.18878537 0.14153615]
 [0.         0.         0.         0.        ]
 [0.45436507 0.4907697  0.33885479 0.61415017]
 [0.42992164 0.66562507 0.41469106 0.27274667]
 [0.62223916 0.43273973 0.37749524 0.2866353 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.52236344 0.48531827 0.74458562 

In [34]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen 
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        # Choose action with highest Q-value for current state     
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        # Take new action

        if done:
            if reward == 1:
                # Agent reached the goal and won episode
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break

        # Set new state
        state = new_state


env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
